### ISSUE TITLE
Release train code

### ISSUE THREAD

**Issue by wangqiang9** [GoFigure-LANL/DeepPatent-dataset#1]
Hi, Thank you for your creative work!
It seems that you only released the test code and pretrained model, but did not release the train code. Is there any plan to release the train code? Thank you a lot!

**Comment by MisoKucer** [comment]
Hi there,

I appreciate your interest in our work. We do not plan to release training code in the near future (next 3 months), as the code has to go through an internal review and the authors are currently preoccupied with other project.
